#!/usr/bin/env bash
#Creating a script that uses a while loop with if, elif and else
x=1
while [ $x -le 10 ]
do
	if [ $x = 4 ]
	then
		echo "bad luck"
	elif [ $x = 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	x=$((x + 1))
done
